Xync-Automation: 
  name: 'Xync-Automation'
  type: 'Rune'
  max-level: 3
  skill-req-lvl: 1
  needs-permission: 'false'
  attributes: 
    level-base: '1'
    level-scale: '0'
    cost-base: '1'
    cost-scale: '0'
    cooldown-base: '0'
    cooldown-scale: '0'
    mana-base: '0'
    mana-scale: '0'
    points-spent-req-base: '0'
    points-spent-req-scale: '0'
    incompatible: 
    - ''
  msg: '&6{player} &2has cast &6{skill}'
  icon: 'GOLD_BLOCK'
  icon-durability: 0
  icon-data: 0
  icon-lore: 
  - '&d{name}'
  - ''
  - '&eSetting for your Xync Rune Option.'
  - '&eLeft click to increase, Right Click to Decrease.'
  - '&aCurrent Mode: &b[{level}]'
  - ''
  - '&dMode 1: &cShield Upgrade'
  - '&6Skill Addon; &9+Invincibility'
  - '&7Adds a 2 second Invincibility to'
  - '&7Forcefield, and Surge Shield.'
  - ''
  - '&dMode 2: &cGrace Period'
  - '&6Skill Addon; &9+Passive'
  - '&7Adds a 2 second Invincibility to'
  - '&7Self-Destruct.'
  - ''
  - '&dMode 3: &cProtected Boost'
  - '&6Skill Addon; &9+Shield'
  - '&7Take 50% less damage for 3 seconds'
  - '&7after casting Thruster Uppercut'
  desc:  []
  components: 
    Initialize: 
      type: 'trigger'
      indicator: '3D'
      data: 
        icon-key: ''
        indicator: '2D'
      children: 
        Value Set-b: 
          type: 'mechanic'
          indicator: '3D'
          data: 
            icon-key: ''
            counts: 'True'
            key: 'value'
            value-base: '1'
            value-scale: '0'
            indicator: '2D'
          children:  {}
