Yryn-Automation: 
  name: 'Yryn-Automation'
  type: 'Rune'
  max-level: 3
  skill-req-lvl: 1
  needs-permission: 'false'
  attributes: 
    level-base: '1'
    level-scale: '0'
    cost-base: '1'
    cost-scale: '0'
    cooldown-base: '0'
    cooldown-scale: '0'
    mana-base: '0'
    mana-scale: '0'
    points-spent-req-base: '0'
    points-spent-req-scale: '0'
    incompatible: 
    - ''
  msg: '&6{player} &2has cast &6{skill}'
  icon: 'DIAMOND_BLOCK'
  icon-durability: 0
  icon-data: 0
  icon-lore: 
  - '&d{name}'
  - ''
  - '&eSetting for your Yryn Rune Option.'
  - '&eLeft click to increase, Right Click to Decrease.'
  - '&aCurrent Mode: &b[{level}]'
  - ''
  - '&dMode 1: &cBetter Chances'
  - '&6Skill Addon; &9+Healing'
  - '&7Heal some HP after casting Self-Destruct.'
  - ''
  - '&dMode 2: &cMedic Shields'
  - '&6Skill Addon; &9+Healing'
  - '&7Heal some HP and Mana after casting Forcefield.'
  - ''
  - '&dMode 3: &cQuick Tech'
  - '&6Skill Addon; &9+Tech'
  - '&7Gain 10 Tech after casting Thruster Uppercut'
  - '&7and Nano Repair, and 25 Tech for Overdrive.'
  desc:  []
  components: 
    Initialize: 
      type: 'trigger'
      indicator: '3D'
      data: 
        icon-key: ''
        indicator: '2D'
      children: 
        Value Set-b: 
          type: 'mechanic'
          indicator: '3D'
          data: 
            icon-key: ''
            counts: 'True'
            key: 'value'
            value-base: '1'
            value-scale: '0'
            indicator: '2D'
          children:  {}
