Alby-Automation: 
  name: 'Alby-Automation'
  type: 'Rune'
  max-level: 3
  skill-req-lvl: 1
  needs-permission: 'false'
  attributes: 
    level-base: '1'
    level-scale: '0'
    cost-base: '1'
    cost-scale: '0'
    cooldown-base: '0'
    cooldown-scale: '0'
    mana-base: '0'
    mana-scale: '0'
    points-spent-req-base: '0'
    points-spent-req-scale: '0'
    incompatible: 
    - ''
  msg: '&6{player} &2has cast &6{skill}'
  icon: 'REDSTONE_BLOCK'
  icon-durability: 0
  icon-data: 0
  icon-lore: 
  - '&d{name}'
  - ''
  - '&eSetting for your Alby Rune Option.'
  - '&eLeft click to increase, Right Click to Decrease.'
  - '&aCurrent Mode: &b[{level}]'
  - ''
  - '&dMode 1: &cCryo Chip'
  - '&6Skill Addon; &9+Damage'
  - '&7Power Shot and Missile deals additional Water'
  - '&7damage, and grants Slowness 3 for 6 Seconds.'
  - ''
  - '&dMode 2: &cShock Chip'
  - '&6Skill Addon; &9+Damage'
  - '&7Adds Electrical Piercing damage to'
  - '&7Rapid Blast, and Missile.'
  - ''
  - '&dMode 3: &cPyro Chip'
  - '&6Skill Addon; &9+Projectile'
  - '&7Adds Fire damage to Rapid Blast'
  - '&7and Power shot, that also ignites'
  - '&7hit enemies for 3 Seconds.'
  desc:  []
  components: 
    Initialize: 
      type: 'trigger'
      indicator: '3D'
      data: 
        icon-key: ''
        indicator: '2D'
      children: 
        Value Set-b: 
          type: 'mechanic'
          indicator: '3D'
          data: 
            icon-key: ''
            counts: 'True'
            key: 'value'
            value-base: '1'
            value-scale: '0'
            indicator: '2D'
          children:  {}
