Nrik-Automation: 
  name: 'Nrik-Automation'
  type: 'Rune'
  max-level: 3
  skill-req-lvl: 1
  needs-permission: 'false'
  attributes: 
    level-base: '1'
    level-scale: '0'
    cost-base: '1'
    cost-scale: '0'
    cooldown-base: '0'
    cooldown-scale: '0'
    mana-base: '0'
    mana-scale: '0'
    points-spent-req-base: '0'
    points-spent-req-scale: '0'
    incompatible: 
    - ''
  msg: '&6{player} &2has cast &6{skill}'
  icon: 'EMERALD_BLOCK'
  icon-durability: 0
  icon-data: 0
  icon-lore: 
  - '&d{name}'
  - ''
  - '&eSetting for your Nrik Rune Option.'
  - '&eLeft click to increase, Right Click to Decrease.'
  - '&aCurrent Mode: &b[{level}]'
  - ''
  - '&dMode 1: &cHealthy Stimulation'
  - '&6Skill Addon; &9+Buffs'
  - '&7Adds a 20% damage increase buff to'
  - '&7Surging Shield. Same duration as'
  - '&7the defense buff.'
  - ''
  - '&dMode 2: &cHappy Missile'
  - '&6Skill Addon; &9+Buffs'
  - '&7Grants Speed 1, and a 12% Damage and Defense'
  - '&7buff to allies hit by Missile for 10 Seconds.'
  - ''
  - '&dMode 3: &cHyper Thrust'
  - '&6Skill Addon; &9+Mobility'
  - '&7Thrusting Uppercut launches the caster higher,'
  - '&7and grants Speed 1 for 8 seconds after casting it.'
  desc:  []
  components: 
    Initialize: 
      type: 'trigger'
      indicator: '3D'
      data: 
        icon-key: ''
        indicator: '2D'
      children: 
        Value Set-b: 
          type: 'mechanic'
          indicator: '3D'
          data: 
            icon-key: ''
            counts: 'True'
            key: 'value'
            value-base: '1'
            value-scale: '0'
            indicator: '2D'
          children:  {}
