Automation: 
  name: 'Automation'
  action-bar: ''
  prefix: '&6Automation'
  group: 'class'
  mana: '&2Mana'
  max-level: 1
  parent: 'Citizen'
  needs-permission: 'false'
  attributes: 
    health-base: '900'
    health-scale: '0'
    mana-base: '1000'
    mana-scale: '0'
    staminabonus-base: '100'
    staminabonus-scale: '0'
    staminabonusminusone-base: '99'
    staminabonusminusone-scale: '0'
    basespeed-base: '0'
    basespeed-scale: '0'
    weight-base: '120'
    weight-scale: '0'
    naturalmanaregen-base: '30'
    naturalmanaregen-scale: '0'
  mana-regen: 0.0
  tree: 'FLOOD'
  blacklist:  []
  skills: 
  - 'Light Combo Automation'
  - 'Heavy Combo Automation'
  - 'Thruster Uppercut'
  - 'Forcefield'
  - 'Missile'
  - 'Flamethrower'
  - 'Nano-Repair'
  - 'Rapid Blast'
  - 'Power Shot'
  - 'Surging Shield'
  - 'Overdrive'
  - 'Self-Destruct'
  - 'Electric Fence'
  - 'Electric Net'
  - 'EMP Blast'
  - 'Triple Blast'
  - 'External Hull'
  - 'Auto-Repair'
  - 'Metal Body'
  - 'Alby-Automation'
  - 'Xync-Automation'
  - 'Yryn-Automation'
  - 'Nrik-Automation'
  - 'Araw-Automation'
  - 'Redirect Systems'
  icon: 'ARMOR_STAND'
  icon-durability: 0
  icon-data: 0
  icon-lore: 
  - '&dAutomation'
  exp-source: 511
